# corridor_only — 每层只走走廊入口点

kFloor1Waypoints:
  - [0.0, 14.6, 0.6]
  - [0.0, 28.8, 0.6]
  - [0.0, 14.6, 0.6]

kFloor2Waypoints:
  - [0.0, 14.6, 3.2]
  - [0.0, 28.8, 3.2]
  - [0.0, 14.6, 3.2]

kFloor3Waypoints:
  - [0.0, 14.6, 5.8]
  - [0.0, 28.8, 5.8]
  - [0.0, 14.6, 5.8]
